### ISSUE TITLE
Create interface for client to server communication

### ISSUE THREAD

**Issue by clermona** [SE2-Gruppe3/lotti-karotti#51]
Create interface so that developer only has to call for example connect() or disconnectPlayer()

**Comment by bigDegen** [comment]
Hi @aoksy1 ,

For this task, I would recommend you to use our existing "[_NetworkCodes_](https://github.com/SE2-Gruppe3/lotti-karotti/blob/feat/network/app/src/main/java/com/example/lottikarotti/Network/NetworkCodes.java)" file, which contains all of the emit and listening codes for our server, as well as all of the error codes. The file also contains commented code to provide you with additional context and information on how to use these codes.

By using the "NetworkCodes" file, we can ensure that our server code remains consistent and follows best practices for network communication. It also provides a more efficient way to manage the codebase and reduces the risk of introducing errors or inconsistencies in the code.

Please be sure to carefully review the "NetworkCodes" file before starting your work, and reach out if you have any questions or concerns. 

Best regards,
Samuel
